# Change these first
owner: tpaul1611 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: lifeofthomas.com
    url: https://www.lifeofthomas.com
  - name: snake.lifeofthomas.com
    url: https://snake.lifeofthomas.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lifeofthomas.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Thomas Moser's **Upptime** monitor and status page, powered entirely by GitHub."
  introMessage: Uptime monitor and status page, powered entirely by GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tpaul1611/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
